name: '⇻ GitFlow Release Start'

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Target version for this release.'
        required: true
jobs:
  release-start:
    name: Release Start
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Setup git for commits
      run: |
        git config user.name "GitHub Action"
        git config user.email "noreply@github.com"
    - name: Create release branch
      run: |
        mvn gitflow:release-start --batch-mode --no-transfer-progress -DreleaseVersion='${{ github.event.inputs.version }}' -DinstallProject=false
    - name: Create Pull Request
      run: gh pr create -B main -H release/${{ github.event.inputs.version }} --title 'Release ${{ github.event.inputs.version }}' --body 'Release started using GitHub action GitFlow Release Start'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}